import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/fintrack_provider.dart';
import 'locales/en.dart';
import 'locales/es.dart';
import 'locales/fr.dart';
import 'locales/de.dart';
import 'locales/hi.dart';
import 'locales/ta.dart';
import 'locales/ja.dart';

/// Supported locales.
const locales = <AppLocaleMeta>[
  AppLocaleMeta(code: 'en', label: 'English', flag: '🇬🇧', nativeName: 'English'),
  AppLocaleMeta(code: 'es', label: 'Español', flag: '🇪🇸', nativeName: 'Español'),
  AppLocaleMeta(code: 'fr', label: 'Français', flag: '🇫🇷', nativeName: 'Français'),
  AppLocaleMeta(code: 'de', label: 'Deutsch', flag: '🇩🇪', nativeName: 'Deutsch'),
  AppLocaleMeta(code: 'hi', label: 'हिन्दी', flag: '🇮🇳', nativeName: 'हिन्दी'),
  AppLocaleMeta(code: 'ta', label: 'தமிழ்', flag: '🇮🇳', nativeName: 'தமிழ்'),
  AppLocaleMeta(code: 'ja', label: '日本語', flag: '🇯🇵', nativeName: '日本語'),
];

class AppLocaleMeta {
  final String code, label, flag, nativeName;
  const AppLocaleMeta({required this.code, required this.label, required this.flag, required this.nativeName});
}

class AppT {
  final AppNav nav; final AppCommon common; final AppDashboard dashboard;
  final AppTx tx; final AppBudget budget; final AppAnalytics analytics;
  final AppInsights insights; final AppGoals goals; final AppSubscriptions subscriptions;
  final AppNotes notes; final AppCalculators calculators; final AppCurrency currency;
  final AppReceipts receipts; final AppVoice voice; final AppAiChat aiChat;
  final AppReports reports; final AppNotifications notifications; final AppFamily family;
  final AppProfile profile; final AppSettings settings; final AppOnboarding onboarding;
  final AppMessages messages; final AppSettingsDesc settingsDesc; final AppCalcLabels calcLabels; final AppMisc misc;
  const AppT({required this.nav, required this.common, required this.dashboard, required this.tx, required this.budget, required this.analytics, required this.insights, required this.goals, required this.subscriptions, required this.notes, required this.calculators, required this.currency, required this.receipts, required this.voice, required this.aiChat, required this.reports, required this.notifications, required this.family, required this.profile, required this.settings, required this.onboarding, required this.messages, required this.settingsDesc, required this.calcLabels, required this.misc});
}

class AppNav { final String finance, tools, account, dashboard, expenses, income, budget, analytics, insights, goals, subscriptions, notes, receipts, voice, aiChat, calculators, currency, reports, notifications, family, profile, settings; const AppNav(this.finance, this.tools, this.account, this.dashboard, this.expenses, this.income, this.budget, this.analytics, this.insights, this.goals, this.subscriptions, this.notes, this.receipts, this.voice, this.aiChat, this.calculators, this.currency, this.reports, this.notifications, this.family, this.profile, this.settings); }
class AppCommon { final String add, save, cancel, delete, edit, search, all, today, yesterday, thisMonth, total, amount, loading, retry, close, confirm, skip, continue_, getStarted, viewAll, manage, create, new_, active, paused, recurring, merchant, date, account, category, expense, income, week, month, year, of, left, remaining, onTrack, approaching, exceeded, saveChanges, addNew; const AppCommon(this.add, this.save, this.cancel, this.delete, this.edit, this.search, this.all, this.today, this.yesterday, this.thisMonth, this.total, this.amount, this.loading, this.retry, this.close, this.confirm, this.skip, this.continue_, this.getStarted, this.viewAll, this.manage, this.create, this.new_, this.active, this.paused, this.recurring, this.merchant, this.date, this.account, this.category, this.expense, this.income, this.week, this.month, this.year, this.of, this.left, this.remaining, this.onTrack, this.approaching, this.exceeded, this.saveChanges, this.addNew); }
class AppDashboard { final String totalNetWorth, monthIncome, monthSpend, savingsRate, activeBudgets, spending7day, budgetHealth, recentTransactions, savingsGoals, aiInsight, liveOverview, dailyExpenseFlow, saved, moneyIn, moneyOut, viewAllInsights, vsLast, allOnTrack, overLimit, onTrackShort; const AppDashboard(this.totalNetWorth, this.monthIncome, this.monthSpend, this.savingsRate, this.activeBudgets, this.spending7day, this.budgetHealth, this.recentTransactions, this.savingsGoals, this.aiInsight, this.liveOverview, this.dailyExpenseFlow, this.saved, this.moneyIn, this.moneyOut, this.viewAllInsights, this.vsLast, this.allOnTrack, this.overLimit, this.onTrackShort); }
class AppTx { final String addExpense, addIncome, editTransaction, totalExpenses, totalIncome, allTime, last7, last30, last90, searchPlaceholder, allCategories, noResults, addFirst, transactionDetails, merchantSource, recurringTx, note; const AppTx(this.addExpense, this.addIncome, this.editTransaction, this.totalExpenses, this.totalIncome, this.allTime, this.last7, this.last30, this.last90, this.searchPlaceholder, this.allCategories, this.noResults, this.addFirst, this.transactionDetails, this.merchantSource, this.recurringTx, this.note); }
class AppBudget { final String budgetCenter, totalBudgeted, used, remaining, newBudget, createBudget, limitAmount, period, weekly, monthly, yearly, rollover, rolloverUnused, yourBudgets, noBudgets, overBudget, approachingLimit; const AppBudget(this.budgetCenter, this.totalBudgeted, this.used, this.remaining, this.newBudget, this.createBudget, this.limitAmount, this.period, this.weekly, this.monthly, this.yearly, this.rollover, this.rolloverUnused, this.yourBudgets, this.noBudgets, this.overBudget, this.approachingLimit); }
class AppAnalytics { final String financialHealth, grade, excellent, great, good, fair, needsWork, totalIncome, totalExpenses, netBalance, savingsRate, spendingByCategory, topCategories, whereMoneyGoes, incomeVsExpenses, last6Months, cashFlowTrend, netPerMonth; const AppAnalytics(this.financialHealth, this.grade, this.excellent, this.great, this.good, this.fair, this.needsWork, this.totalIncome, this.totalExpenses, this.netBalance, this.savingsRate, this.spendingByCategory, this.topCategories, this.whereMoneyGoes, this.incomeVsExpenses, this.last6Months, this.cashFlowTrend, this.netPerMonth); }
class AppInsights { final String aiFinancialInsights, monthEndForecast, weeklySummary, anomalies, personalizedInsights, generatedBy, trendingUp, trendingDown, steady, confidence, daysRemaining, projectedTotalSpend, spent, earned, topCategory, allClear, noUnusual, vsLastWeek, saveAsNotification, refresh, low, medium, high; const AppInsights(this.aiFinancialInsights, this.monthEndForecast, this.weeklySummary, this.anomalies, this.personalizedInsights, this.generatedBy, this.trendingUp, this.trendingDown, this.steady, this.confidence, this.daysRemaining, this.projectedTotalSpend, this.spent, this.earned, this.topCategory, this.allClear, this.noUnusual, this.vsLastWeek, this.saveAsNotification, this.refresh, this.low, this.medium, this.high); }
class AppGoals { final String savingsGoals, totalSaved, ofTarget, newGoal, createSavingsGoal, goalName, targetAmount, deadline, icon, color, addMoney, goalReached, toGo, daysLeft, noGoals, createGoal, targetReached; const AppGoals(this.savingsGoals, this.totalSaved, this.ofTarget, this.newGoal, this.createSavingsGoal, this.goalName, this.targetAmount, this.deadline, this.icon, this.color, this.addMoney, this.goalReached, this.toGo, this.daysLeft, this.noGoals, this.createGoal, this.targetReached); }
class AppSubscriptions { final String subscriptionTracker, monthlyCost, perYear, perMonth, active, cancelled, addSubscription, nextRenewal, daysLeft, renewsToday, paused, pause, resume, noSubscriptions, aiTip, addSubscriptionTitle, name; const AppSubscriptions(this.subscriptionTracker, this.monthlyCost, this.perYear, this.perMonth, this.active, this.cancelled, this.addSubscription, this.nextRenewal, this.daysLeft, this.renewsToday, this.paused, this.pause, this.resume, this.noSubscriptions, this.aiTip, this.addSubscriptionTitle, this.name); }
class AppNotes { final String financialNotes, newNote, searchNotes, allNotes, pinned, noNotes, createFirst, title, body, tags; const AppNotes(this.financialNotes, this.newNote, this.searchNotes, this.allNotes, this.pinned, this.noNotes, this.createFirst, this.title, this.body, this.tags); }
class AppCalculators { final String calculatorHub, basic, emi, gst, sip, financialCalculators, smarterDecisions, loanAmount, interestRate, tenure, monthlyEmi, totalInterest, totalPayable, addGst, removeGst, baseAmount, gstSlab, gstAmount, cgst, sgst, monthlyInvestment, expectedReturn, maturityValue, totalInvested, totalGains, period; const AppCalculators(this.calculatorHub, this.basic, this.emi, this.gst, this.sip, this.financialCalculators, this.smarterDecisions, this.loanAmount, this.interestRate, this.tenure, this.monthlyEmi, this.totalInterest, this.totalPayable, this.addGst, this.removeGst, this.baseAmount, this.gstSlab, this.gstAmount, this.cgst, this.sgst, this.monthlyInvestment, this.expectedReturn, this.maturityValue, this.totalInvested, this.totalGains, this.period); }
class AppCurrency { final String currencyConverter, realTimeRates, from, to, swap, quickAmounts, rate, popularPairs, dayTrend, liveRates, cachedDemo; const AppCurrency(this.currencyConverter, this.realTimeRates, this.from, this.to, this.swap, this.quickAmounts, this.rate, this.popularPairs, this.dayTrend, this.liveRates, this.cachedDemo); }
class AppReceipts { final String receiptScanner, receiptIntelligence, uploadCapture, uploadImage, takePhoto, trySample, receiptPreview, readyToScan, scanReceipt, readingReceipt, reviewConfirm, extracted, detectedItems, subtotal, tax, aiCategory, saveExpense, chooseAnother, scanAnother, snapReceipt, chooseAnother2; const AppReceipts(this.receiptScanner, this.receiptIntelligence, this.uploadCapture, this.uploadImage, this.takePhoto, this.trySample, this.receiptPreview, this.readyToScan, this.scanReceipt, this.readingReceipt, this.reviewConfirm, this.extracted, this.detectedItems, this.subtotal, this.tax, this.aiCategory, this.saveExpense, this.chooseAnother, this.scanAnother, this.snapReceipt, this.chooseAnother2); }
class AppVoice { final String voiceExpenseEntry, naturalLanguageCapture, tapToRecord, listening, stopRecording, understanding, whatYouSaid, reviewConfirm, recordAgain, parsed, howItWorks, recordedOnDevice, transcribedByAsr, parsedByAi; const AppVoice(this.voiceExpenseEntry, this.naturalLanguageCapture, this.tapToRecord, this.listening, this.stopRecording, this.understanding, this.whatYouSaid, this.reviewConfirm, this.recordAgain, this.parsed, this.howItWorks, this.recordedOnDevice, this.transcribedByAsr, this.parsedByAi); }
class AppAiChat { final String aiFinancialCoach, askLumina, groundedInData, clear, send, askAboutFinances, clearConversation, canAnalyze, suggestions; const AppAiChat(this.aiFinancialCoach, this.askLumina, this.groundedInData, this.clear, this.send, this.askAboutFinances, this.clearConversation, this.canAnalyze, this.suggestions); }
class AppReports { final String reportsExport, exportPdf, exportCsv, dateRange, financialSummary, print, spendingByCategory, incomeSources, thisYear, summary; const AppReports(this.reportsExport, this.exportPdf, this.exportCsv, this.dateRange, this.financialSummary, this.print, this.spendingByCategory, this.incomeSources, this.thisYear, this.summary); }
class AppNotifications { final String notifications, markAllRead, all, unread, info, alerts, ai, noNotifications; const AppNotifications(this.notifications, this.markAllRead, this.all, this.unread, this.info, this.alerts, this.ai, this.noNotifications); }
class AppFamily { final String familyAccounts, sharedFinances, inviteMember, familyOverview, members, sharedBudgets, permissions, admin, member, viewer, you, inviteSent, totalFamilyBalance, email, role; const AppFamily(this.familyAccounts, this.sharedFinances, this.inviteMember, this.familyOverview, this.members, this.sharedBudgets, this.permissions, this.admin, this.member, this.viewer, this.you, this.inviteSent, this.totalFamilyBalance, this.email, this.role); }
class AppProfile { final String profile, editProfile, linkedAccounts, memberSince, financialSnapshot, name, email, baseCurrency, monthlyIncomeGoal, avatarColor, netWorth, savingsRate, incomeVsGoal; const AppProfile(this.profile, this.editProfile, this.linkedAccounts, this.memberSince, this.financialSnapshot, this.name, this.email, this.baseCurrency, this.monthlyIncomeGoal, this.avatarColor, this.netWorth, this.savingsRate, this.incomeVsGoal); }
class AppSettings { final String settings, appearance, theme, dark, light, preferences, language, defaultView, notificationsSection, budgetAlerts, billReminders, aiInsights, weeklySummary, security, biometric, changePin, changePassword, data, exportData, resetDemo, deleteAccount, about, version, privacyPolicy, terms, luminaDesign, languageUpdated; const AppSettings(this.settings, this.appearance, this.theme, this.dark, this.light, this.preferences, this.language, this.defaultView, this.notificationsSection, this.budgetAlerts, this.billReminders, this.aiInsights, this.weeklySummary, this.security, this.biometric, this.changePin, this.changePassword, this.data, this.exportData, this.resetDemo, this.deleteAccount, this.about, this.version, this.privacyPolicy, this.terms, this.luminaDesign, this.languageUpdated); }
class AppOnboarding { final String welcomeTitle, welcomeBody, clarityTitle, clarityBody, coachTitle, coachBody, securityTitle, securityBody; const AppOnboarding(this.welcomeTitle, this.welcomeBody, this.clarityTitle, this.clarityBody, this.coachTitle, this.coachBody, this.securityTitle, this.securityBody); }
class AppMessages { final String enterAmount, pickCategory, txUpdated, txDeleted, noteDeleted, noteUpdated, noteCreated, untitled, subRemoved, enterNameAmount, subAdded, txParsed, enterValidAmount, aiRequestFailed, noTxInRange, openingPrint, uploadImageOnly, imageTooLarge, sampleLoadFailed, receiptScanned, profileUpdated, goalDeleted, enterGoalTarget, invalidBackup, dataRestored, fileReadError, openingLicenses, dataExported, backupImported, weeklyGenerated, networkError, couldNotGenerate, importBackup, restoreFromJson, import_, updatePersonalDetails, manageYourData, downloadJson, restoreOriginal, permanentlyRemove, addedToGoal, expenseLoggedReceipt, txExportedCsv, alertsOnOff, biometricStatus, enterEmail, onState, offState; const AppMessages(this.enterAmount, this.pickCategory, this.txUpdated, this.txDeleted, this.noteDeleted, this.noteUpdated, this.noteCreated, this.untitled, this.subRemoved, this.enterNameAmount, this.subAdded, this.txParsed, this.enterValidAmount, this.aiRequestFailed, this.noTxInRange, this.openingPrint, this.uploadImageOnly, this.imageTooLarge, this.sampleLoadFailed, this.receiptScanned, this.profileUpdated, this.goalDeleted, this.enterGoalTarget, this.invalidBackup, this.dataRestored, this.fileReadError, this.openingLicenses, this.dataExported, this.backupImported, this.weeklyGenerated, this.networkError, this.couldNotGenerate, this.importBackup, this.restoreFromJson, this.import_, this.updatePersonalDetails, this.manageYourData, this.downloadJson, this.restoreOriginal, this.permanentlyRemove, this.addedToGoal, this.expenseLoggedReceipt, this.txExportedCsv, this.alertsOnOff, this.biometricStatus, this.enterEmail, this.onState, this.offState); }
class AppSettingsDesc { final String appearanceSub, switchTheme, preferencesSub, appLanguage, usedForAmounts, defaultViewDesc, notifSub, budgetAlertsDesc, billRemindersDesc, aiInsightsDesc, weeklySummaryDesc, securitySub, biometricDesc, pinDesc, passwordDesc, aboutSub, privacyDesc, termsDesc; const AppSettingsDesc(this.appearanceSub, this.switchTheme, this.preferencesSub, this.appLanguage, this.usedForAmounts, this.defaultViewDesc, this.notifSub, this.budgetAlertsDesc, this.billRemindersDesc, this.aiInsightsDesc, this.weeklySummaryDesc, this.securitySub, this.biometricDesc, this.pinDesc, this.passwordDesc, this.aboutSub, this.privacyDesc, this.termsDesc); }
class AppCalcLabels { final String loanDetails, loanDetailsSub, gstInputs, gstInputsSub, basicSub; const AppCalcLabels(this.loanDetails, this.loanDetailsSub, this.gstInputs, this.gstInputsSub, this.basicSub); }
class AppMisc { final String tapPairToLoad, sixMonthTrend, neverMissRenewal, importantHappensHere, setTargetWatchGrow, addExpensesToSeeBreakdown, addIncomeToSeeSources, peopleInFamily, trackFamilySpending, sipSavingsPlan, projectCompoundingReturns; const AppMisc(this.tapPairToLoad, this.sixMonthTrend, this.neverMissRenewal, this.importantHappensHere, this.setTargetWatchGrow, this.addExpensesToSeeBreakdown, this.addIncomeToSeeSources, this.peopleInFamily, this.trackFamilySpending, this.sipSavingsPlan, this.projectCompoundingReturns); }

final Map<String, AppT> _dict = {
  'en': enT, 'es': esT, 'fr': frT, 'de': deT, 'hi': hiT, 'ta': taT, 'ja': jaT,
};

AppT getT(String? locale) => _dict[locale] ?? enT;

final tProvider = Provider<AppT>((ref) {
  final locale = ref.watch(fintrackProvider.select((s) => s.locale));
  return getT(locale);
});
